version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrum-master-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TZ=Asia/Tokyo
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
